# GitHub Actions Workflow to generate documents and slides and publish them to GitHub Pages

name: Documents Pipeline

on:
  push:

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  slides:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: 'recursive'
      - name: Generate HTML Slides with Asciidoctor reveal.js
        run: scripts/build-html.sh
      - name: Generate PDF from HTML Slides with decktape
        run: scripts/build-pdf.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: slides
          path: |
            *.html
            pdf/*
          if-no-files-found: error
