# GitHub Actions Workflow to generate documents and slides and publish them to GitHub Pages

name: Documents Pipeline

on:
  push:
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:

  slides:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: 'recursive'
      - name: Make writable PDF directory # otherwise not writable by decktape container user
        run: |
          mkdir -v pdf
          chmod ogu+rw pdf
      - name: Generate HTML Slides with Asciidoctor reveal.js
        run: scripts/build-html.sh
      - name: Upload HTML artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html
          path: |
            *.html
            reveal.js/dist/**
            reveal.js/plugin/**
          if-no-files-found: error
      - name: Create HTML archive
        run: zip -r -q html.zip *.html reveal.js/dist reval.js/plugin
      - name: Generate PDF from HTML Slides with decktape
        run: scripts/build-pdf.sh
      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: pdf/*
          if-no-files-found: error
      - name: Generate README.html
        run: scripts/build-readme.sh
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request' || startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}_${{ github.sha }}
          files: |
            README.html
            html.zip
            pdf/*
